version: "3.9"

services:

  config-server:
    image: ghcr.io/prakashh45/config-server:latest
    container_name: config-server
    restart: unless-stopped
    ports:
      - "8888:8888"

  discovery-server:
    image: ghcr.io/prakashh45/discovery-server:latest
    container_name: discovery-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    image: ghcr.io/prakashh45/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - discovery-server
      - auth-service
      - catalog-service

  auth-service:
    image: ghcr.io/prakashh45/auth-service:latest
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/washgo_db
      SPRING_DATASOURCE_USERNAME: washgo
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - discovery-server

  catalog-service:
    image: ghcr.io/prakashh45/catalog-service:latest
    container_name: catalog-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/washgo_db
      SPRING_DATASOURCE_USERNAME: washgo
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - discovery-server

  order-service:
    image: ghcr.io/prakashh45/order-service:latest
    container_name: order-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/washgo_db
      SPRING_DATASOURCE_USERNAME: washgo
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - discovery-server

networks:
  default:
    name: washgo-network