version: "3.9"

services:

  config-server:
    image: ghcr.io/prakashh45/config-server:latest
    container_name: config-server
    restart: unless-stopped
    ports:
      - "8888:8888"

  discovery-server:
    image: ghcr.io/prakashh45/discovery-server:latest
    container_name: discovery-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    image: ghcr.io/prakashh45/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - auth-service
      - catalog-service
      - order-service

  auth-service:
    image: ghcr.io/prakashh45/auth-service:latest
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server

  catalog-service:
    image: ghcr.io/prakashh45/catalog-service:latest
    container_name: catalog-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server

  order-service:
    image: ghcr.io/prakashh45/order-service:latest
    container_name: order-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server

networks:
  default:
    name: washgo-network