spring.application.name=payment-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/washgo_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:washgo}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

order.base-url=${ORDER_BASE_URL:http://order-service:8083}

razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}
razorpay.currency=${RAZORPAY_CURRENCY:INR}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
