spring.application.name=order-service
spring.config.import=configserver:http://config-server:8888


# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
management.metrics.tags.application=${spring.application.name}