# ==========================================
# APPLICATION
# ==========================================
spring.application.name=CONFIG-SERVER

server.port=8888


# ==========================================
# EUREKA
# ==========================================
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ==========================================
# CONFIG SERVER
# ==========================================
spring.cloud.config.server.git.uri=https://github.com/prakashh45/washgo-config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=*
